package modelo;
// Generated 13/06/2021 02:25:10 PM by Hibernate Tools 4.3.1



/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable {


     private Integer iddoctorRick;
     private String nombreRick;
     private byte edadRick;
     private String especialidadRick;
     private String cargoRick;
     private String telefonoRick;
     private String cedulaRick;

    public Doctor() {
    }

    public Doctor(String nombreRick, byte edadRick, String especialidadRick, String cargoRick, String telefonoRick, String cedulaRick) {
       this.nombreRick = nombreRick;
       this.edadRick = edadRick;
       this.especialidadRick = especialidadRick;
       this.cargoRick = cargoRick;
       this.telefonoRick = telefonoRick;
       this.cedulaRick = cedulaRick;
    }
   
    public Integer getIddoctorRick() {
        return this.iddoctorRick;
    }
    
    public void setIddoctorRick(Integer iddoctorRick) {
        this.iddoctorRick = iddoctorRick;
    }
    public String getNombreRick() {
        return this.nombreRick;
    }
    
    public void setNombreRick(String nombreRick) {
        this.nombreRick = nombreRick;
    }
    public byte getEdadRick() {
        return this.edadRick;
    }
    
    public void setEdadRick(byte edadRick) {
        this.edadRick = edadRick;
    }
    public String getEspecialidadRick() {
        return this.especialidadRick;
    }
    
    public void setEspecialidadRick(String especialidadRick) {
        this.especialidadRick = especialidadRick;
    }
    public String getCargoRick() {
        return this.cargoRick;
    }
    
    public void setCargoRick(String cargoRick) {
        this.cargoRick = cargoRick;
    }
    public String getTelefonoRick() {
        return this.telefonoRick;
    }
    
    public void setTelefonoRick(String telefonoRick) {
        this.telefonoRick = telefonoRick;
    }
    public String getCedulaRick() {
        return this.cedulaRick;
    }
    
    public void setCedulaRick(String cedulaRick) {
        this.cedulaRick = cedulaRick;
    }




}


